### ISSUE TITLE
Demo ready: feedback to incorporate for demo video

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#137]
In order of priority:

Must haves-

- [x] Tagging a message shows error
![image](https://user-images.githubusercontent.com/16714604/86572605-c89ab780-bf90-11ea-8dfc-b956e8064328.png)

- [x] Untag func. also needed

- [x] after searching, clicking on the results refreshes the screen and starts showing all the chats (#138)

- [x] speed sends and tags screen to be designed (#140 & #139)
- Move the actions column towards right
- Change the add new button to make it similar to 'Send' button

- [x] Spacing in the chats and navigation columns need to be adjusted (#144)

- [x] modals/pop up to be designed to be in sync (#123 for speed sends)
- Going with the checkbox list format for now. `Confirm` and `Cancel` buttons can be as per the designs? and the search input field.

Good to haves-

- [x] allow search by entering the number partially (#141)

- [x] loader to have some margin at the top(#142)

- [x] we can fix the favicon also. will upload the image (#143)

Would like but not a blocker

- [x] Longer message text to appear in multiple lines instead of getting cropped. Also using SHIFT key to give a line break (#126)

- [x] on collapsing the sidebar, the color of the highlighted item changes

- [x] on searching, the results should filter real time. this would remove the requirement of 'Enter' or Submit action (#157)

**Comment by abhi1203** [comment]
- [ ] There's a horizontal scroll on the screen:
![image](https://user-images.githubusercontent.com/16714604/86733891-30173c80-c04f-11ea-94af-83734566bbb2.png)
I tried to zoom out for the recording, which was fine till i send a message. whenever i send a message the screen hides again.
