### ISSUE TITLE
Glific v0.2 feature review feedback

### ISSUE THREAD

**Issue by abhi1203** [glific/glific-frontend#236]
- [x] All is missing so once a collection is selected, I'm not able to go to all chats
![image](https://user-images.githubusercontent.com/16714604/88668121-d52dae00-d0ff-11ea-8ff7-7179a85fd42d.png)
Also, please use a lowercase 'r' in Not Replied

- [x] The messages are appearing reversed https://github.com/glific/glific/issues/322 and #265 
![image](https://user-images.githubusercontent.com/16714604/88668667-8cc2c000-d100-11ea-90e7-23c99844a5b4.png)

- [x] If I use the button to send a message, the input box doesn't empty
![image](https://user-images.githubusercontent.com/16714604/88668900-d7443c80-d100-11ea-81e4-a9493dd2f806.png)

- [x] Not able to see the speed sends option in the chat window
![image](https://user-images.githubusercontent.com/16714604/88672437-15435f80-d105-11ea-9064-003368be1e35.png)

- [x] It appears that the unread messages are not filtering. Chat with Abhishek is unread but on clicking Unread option, it says not available chats.

![image](https://user-images.githubusercontent.com/16714604/88673148-e5488c00-d105-11ea-86dd-b7af4efc9ff7.png)
![image](https://user-images.githubusercontent.com/16714604/88673192-f1cce480-d105-11ea-9424-415f638b2aad.png)

- [x] The sorry message should appear first as per the flow but in the message it shows after https://github.com/glific/glific/issues/321
![image](https://user-images.githubusercontent.com/16714604/88674931-0611e100-d108-11ea-892f-d83ddb115017.png)
![IMG_4E7CFEBE1F23-1](https://user-images.githubusercontent.com/16714604/88674731-cba84400-d107-11ea-9bb5-fd56f0da39e2.jpeg)

- [x] Not sure what this hello chat is under 'not replied'
![image](https://user-images.githubusercontent.com/16714604/88675340-7882c100-d108-11ea-88c2-9a002cd8f51b.png)
![image](https://user-images.githubusercontent.com/16714604/88675373-7f113880-d108-11ea-9be7-782bac5f02f0.png)

- [x] On sending optout I didn't receive any message on whatapp. But on glific the flow continues https://github.com/glific/glific/issues/323
![IMG_823041C4EC58-1](https://user-images.githubusercontent.com/16714604/88675648-c3043d80-d108-11ea-80ae-60f389808cfa.jpeg)
![image](https://user-images.githubusercontent.com/16714604/88675542-a831c900-d108-11ea-8cbf-dada3360ed76.png)

- [x] For the first chat to show, we still have to refresh for it to appear. Can we please fix that, it would be helpful while recording the video. #160 
![image](https://user-images.githubusercontent.com/16714604/88676728-0f9c4880-d10a-11ea-844e-6f289a83f66d.png)

- [x] The alignment of the actions and body content doesn't render properly. #239 
![image](https://user-images.githubusercontent.com/16714604/88677543-0b245f80-d10b-11ea-84f2-b4a6531ea3f7.png)

- [x] Can we position the emoji below the text so that it doesn't overlap with text #258 
![image](https://user-images.githubusercontent.com/16714604/88679487-18dae480-d10d-11ea-9766-bffc03210f28.png)

- [x] On delete template modal: #240
1. the template word needs to be complete
2.. let's change the subtext to: `It will stop showing when you draft a customized message`
![image](https://user-images.githubusercontent.com/16714604/88680074-bb936300-d10d-11ea-9817-6c30574f9246.png)

- [x] Let's change the configure icon on Automations screen - #241
![image](https://user-images.githubusercontent.com/16714604/88681841-a0c1ee00-d10f-11ea-9d3a-6a6617ca8c7d.png)
I've updated the design file with a gear icon = Icons/Configure/Unselected Dark

- [x] Selecting emoji doesn't add it into the input box
![image](https://user-images.githubusercontent.com/16714604/88668016-b5968580-d0ff-11ea-8c1a-80c2dfff801f.png)

- [x] Change it to 'Tags' in the sidebar #246 
![image](https://user-images.githubusercontent.com/16714604/88668961-ec20d000-d100-11ea-91fd-0fe64a0e8edb.png)
Also please check the font weight of the sidebar menu items. Let's use the medium weight.

- [x] Let's fix this pagination to the bottom of the page. Also the background colors don't match. #276
![image](https://user-images.githubusercontent.com/16714604/88669422-808b3280-d101-11ea-8e65-a88e5c740f56.png)

- [x] I think we can increase the width of tags list and decrease some space so they appear neater. #247 
![image](https://user-images.githubusercontent.com/16714604/88670724-08be0780-d103-11ea-9c77-b49d7f433308.png)
We should probably do the same for Speed sends screen too.

- [x] The last chat is inaccessible on scrolling #248
![image](https://user-images.githubusercontent.com/16714604/88680905-9fdc8c80-d10e-11ea-93ee-708e82be8ef6.png)

- [x] Let's align the error text to the width of the input fields #271 
![image](https://user-images.githubusercontent.com/16714604/88647852-10ba7f00-d0e4-11ea-8a8c-82d117a90bbe.png)

**Comment by abhi1203** [comment]
We can also place a help icon linked to this resource : https://help.nyaruka.com/en/articles/1911210-starting-a-flow
![image](https://user-images.githubusercontent.com/16714604/88809156-6751b700-d1d1-11ea-9193-4308033d0dec.png)

This can give assurance in the demo that our system has provision for all of their questions.

**Comment by abhi1203** [comment]
- [ ] Let's align the numbers vertically centre inside the blocks
![image](https://user-images.githubusercontent.com/16714604/89017164-7ce0f100-d337-11ea-94c8-3b52932af185.png)

- [ ] Searching for Help, Optout, language, isn't showing the right results. It seems that titles are not being searched for right now
![image](https://user-images.githubusercontent.com/16714604/89017744-7010cd00-d338-11ea-9184-4703b5564dd0.png)
![image](https://user-images.githubusercontent.com/16714604/89018018-cf6edd00-d338-11ea-8695-f6d04520c4e1.png)


Good to have:

- [ ] Let's allow there to be a scroll inside this speed sends overlay so that users have option to scroll and see all the speed sends
![image](https://user-images.githubusercontent.com/16714604/89016803-f9270480-d336-11ea-802f-5fa976da200a.png)

- [ ] Possible to have rounded corners initially? and only when the speed sends overlay opens, we remove the roundedness
![image](https://user-images.githubusercontent.com/16714604/89016987-4014fa00-d337-11ea-8587-cb2f4b8a3367.png)

- [ ] Clicking once on Unread filters the list to show all unread chats. Then clicking again shows all the conversations. Let's remove the second click action on the collections section. Users can simply click on all or any other option to switch the list. 
Also because when none of the options are selected, it confusing as to what is showing now.
![image](https://user-images.githubusercontent.com/16714604/89017498-04c6fb00-d338-11ea-8996-f6d9ea54dd9d.png)
![image](https://user-images.githubusercontent.com/16714604/89017570-22946000-d338-11ea-8d09-c89e5cdb72e2.png)

**Comment by kurund** [comment]
All done 👍
